### ISSUE TITLE
Width of the HTML report

### ISSUE THREAD

**Issue by thomasw-mitutoyo-ctl** [EveryOtherUsernameWasAlreadyTaken/TaskJugglerInstaller#12]
The width of the HTML report ought to be changed with the [width property ](http://taskjuggler.org/tj3/manual/width.html). However, it seems that the scrollbar prevents a full screen view.

The width can be changed in tjreport.css using !important

```
.tabback {
  background-color:#9a9a9a;
  overflow:visible;
  position:relative; 
  overflow:auto; 
  width:1300px !important;
}
```

Is there a chance to have this included in the TJP file itself? Otherwise people might perhaps want to change the default template in the taskjuggler gem (...\ruby\gems\2.2.0\gems\taskjuggler-3.5.0\data\css\tjreport.css).

**Comment by EveryOtherUsernameWasAlreadyTaken** [comment]
The width property can be applied in several places. Inside `taskreport`, it's not so useful. However, 
```
chart { ${TaskTip} width 1070 }
```
as used in bugfix #4 seems to fix the issue without need of changing the CSS.
